"""create_all_tables

Revision ID: a3b15996ec7b
Revises: 
Create Date: 2026-06-13 02:27:48.257288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3b15996ec7b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actors',
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('actor_type', sa.String(length=64), nullable=False),
    sa.Column('default_language', sa.String(length=16), nullable=True),
    sa.Column('contact_channels_json', sa.JSON(), nullable=False),
    sa.Column('capabilities_json', sa.JSON(), nullable=False),
    sa.Column('profile_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('actor_id')
    )
    op.create_index('ix_actors_actor_type', 'actors', ['actor_type'], unique=False)
    op.create_table('legal_notices',
    sa.Column('notice_id', sa.String(length=36), nullable=False),
    sa.Column('notice_type', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('text_en', sa.String(length=8192), nullable=False),
    sa.Column('text_zh', sa.String(length=8192), nullable=True),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('notice_id')
    )
    op.create_table('schema_registry',
    sa.Column('schema_id', sa.String(length=36), nullable=False),
    sa.Column('industry', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('schema_id')
    )
    op.create_table('unit_dictionary',
    sa.Column('unit_id', sa.String(length=36), nullable=False),
    sa.Column('unit_name', sa.String(length=64), nullable=False),
    sa.Column('unit_symbol', sa.String(length=32), nullable=False),
    sa.Column('unit_type', sa.String(length=64), nullable=False),
    sa.Column('conversion_rule_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('unit_id')
    )
    op.create_table('field_definitions',
    sa.Column('field_id', sa.String(length=36), nullable=False),
    sa.Column('schema_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=128), nullable=False),
    sa.Column('normalized_field_name', sa.String(length=128), nullable=False),
    sa.Column('field_type', sa.String(length=32), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('required_level', sa.String(length=32), nullable=False),
    sa.Column('validation_rule_json', sa.JSON(), nullable=False),
    sa.Column('example_values_json', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['schema_id'], ['schema_registry.schema_id'], ),
    sa.PrimaryKeyConstraint('field_id')
    )
    op.create_index('ix_field_definitions_normalized_field_name', 'field_definitions', ['normalized_field_name'], unique=False)
    op.create_table('field_proposals',
    sa.Column('proposal_id', sa.String(length=36), nullable=False),
    sa.Column('schema_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_field_name', sa.String(length=128), nullable=False),
    sa.Column('normalized_field_name', sa.String(length=128), nullable=False),
    sa.Column('field_type', sa.String(length=32), nullable=False),
    sa.Column('suggested_unit', sa.String(length=32), nullable=True),
    sa.Column('business_reason', sa.String(length=1024), nullable=True),
    sa.Column('example_count', sa.Integer(), nullable=False),
    sa.Column('project_count', sa.Integer(), nullable=False),
    sa.Column('supplier_count', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['schema_id'], ['schema_registry.schema_id'], ),
    sa.PrimaryKeyConstraint('proposal_id')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('original_buyer_actor_id', sa.String(length=36), nullable=False),
    sa.Column('main_supplier_actor_id', sa.String(length=36), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('product_summary', sa.String(length=1024), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('product_tier', sa.String(length=32), nullable=False),
    sa.Column('created_by_channel', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['main_supplier_actor_id'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['original_buyer_actor_id'], ['actors.actor_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_index('ix_projects_category', 'projects', ['category'], unique=False)
    op.create_index('ix_projects_created_at', 'projects', ['created_at'], unique=False)
    op.create_index('ix_projects_main_supplier_actor_id', 'projects', ['main_supplier_actor_id'], unique=False)
    op.create_index('ix_projects_original_buyer_actor_id', 'projects', ['original_buyer_actor_id'], unique=False)
    op.create_index('ix_projects_status', 'projects', ['status'], unique=False)
    op.create_table('shop_capability_profiles',
    sa.Column('profile_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('profile_name', sa.String(length=256), nullable=True),
    sa.Column('machines_json', sa.JSON(), nullable=False),
    sa.Column('tooling_inventory_json', sa.JSON(), nullable=False),
    sa.Column('qc_equipment_json', sa.JSON(), nullable=False),
    sa.Column('material_inventory_json', sa.JSON(), nullable=False),
    sa.Column('in_house_processes_json', sa.JSON(), nullable=False),
    sa.Column('outsourced_processes_json', sa.JSON(), nullable=False),
    sa.Column('schedule_summary_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.actor_id'], ),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('artifacts',
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('owner_actor_id', sa.String(length=36), nullable=True),
    sa.Column('artifact_type', sa.String(length=32), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=True),
    sa.Column('file_ref', sa.String(length=1024), nullable=False),
    sa.Column('file_hash', sa.String(length=128), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('product_tier', sa.String(length=32), nullable=False),
    sa.Column('cap_level', sa.String(length=32), nullable=True),
    sa.Column('encryption_enabled', sa.Boolean(), nullable=False),
    sa.Column('dynamic_watermark_enabled', sa.Boolean(), nullable=False),
    sa.Column('secure_viewer_enabled', sa.Boolean(), nullable=False),
    sa.Column('warning_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_actor_id'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('artifact_id')
    )
    op.create_table('cad_requirement_packets',
    sa.Column('packet_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('original_buyer_actor_id', sa.String(length=36), nullable=False),
    sa.Column('main_supplier_actor_id', sa.String(length=36), nullable=True),
    sa.Column('file_refs_json', sa.JSON(), nullable=False),
    sa.Column('source_types_json', sa.JSON(), nullable=False),
    sa.Column('part_summary', sa.String(length=2048), nullable=True),
    sa.Column('material', sa.String(length=256), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('dimensions_json', sa.JSON(), nullable=False),
    sa.Column('tolerance_requirements_json', sa.JSON(), nullable=False),
    sa.Column('surface_finish_requirements_json', sa.JSON(), nullable=False),
    sa.Column('thread_requirements_json', sa.JSON(), nullable=False),
    sa.Column('heat_treatment_requirements_json', sa.JSON(), nullable=False),
    sa.Column('operation_requirements_json', sa.JSON(), nullable=False),
    sa.Column('qc_requirements_json', sa.JSON(), nullable=False),
    sa.Column('packaging_requirements_json', sa.JSON(), nullable=False),
    sa.Column('delivery_deadline', sa.String(length=32), nullable=True),
    sa.Column('missing_information_json', sa.JSON(), nullable=False),
    sa.Column('extraction_confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['main_supplier_actor_id'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['original_buyer_actor_id'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('packet_id')
    )
    op.create_table('dependency_needs',
    sa.Column('dependency_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_by_actor_id', sa.String(length=36), nullable=False),
    sa.Column('dependency_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('required_specs_json', sa.JSON(), nullable=False),
    sa.Column('quantity_required', sa.Float(), nullable=True),
    sa.Column('required_by_date', sa.String(length=32), nullable=True),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('why_needed', sa.String(length=1024), nullable=False),
    sa.Column('candidate_actor_ids_json', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_actor_id'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('dependency_id')
    )
    op.create_table('field_aliases',
    sa.Column('alias_id', sa.String(length=36), nullable=False),
    sa.Column('field_id', sa.String(length=36), nullable=False),
    sa.Column('alias_text', sa.String(length=256), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['field_definitions.field_id'], ),
    sa.PrimaryKeyConstraint('alias_id')
    )
    op.create_table('field_promotion_decisions',
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('proposal_id', sa.String(length=36), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('decided_by', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['proposal_id'], ['field_proposals.proposal_id'], ),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_table('procurement_edges',
    sa.Column('edge_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('from_actor_id', sa.String(length=36), nullable=False),
    sa.Column('to_actor_id', sa.String(length=36), nullable=False),
    sa.Column('edge_type', sa.String(length=64), nullable=False),
    sa.Column('parent_edge_id', sa.String(length=36), nullable=True),
    sa.Column('inquiry_id', sa.String(length=36), nullable=True),
    sa.Column('response_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['from_actor_id'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['parent_edge_id'], ['procurement_edges.edge_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['to_actor_id'], ['actors.actor_id'], ),
    sa.PrimaryKeyConstraint('edge_id')
    )
    op.create_index('ix_procurement_edges_edge_type', 'procurement_edges', ['edge_type'], unique=False)
    op.create_index('ix_procurement_edges_from_actor_id', 'procurement_edges', ['from_actor_id'], unique=False)
    op.create_index('ix_procurement_edges_parent_edge_id', 'procurement_edges', ['parent_edge_id'], unique=False)
    op.create_index('ix_procurement_edges_project_id', 'procurement_edges', ['project_id'], unique=False)
    op.create_index('ix_procurement_edges_status', 'procurement_edges', ['status'], unique=False)
    op.create_index('ix_procurement_edges_to_actor_id', 'procurement_edges', ['to_actor_id'], unique=False)
    op.create_table('structured_requirements',
    sa.Column('requirement_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('source_actor_id', sa.String(length=36), nullable=False),
    sa.Column('source_message_id', sa.String(length=36), nullable=True),
    sa.Column('raw_input_refs_json', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('material', sa.String(length=256), nullable=True),
    sa.Column('specs_json', sa.JSON(), nullable=False),
    sa.Column('deadline', sa.String(length=64), nullable=True),
    sa.Column('destination', sa.String(length=256), nullable=True),
    sa.Column('missing_fields_json', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['source_actor_id'], ['actors.actor_id'], ),
    sa.PrimaryKeyConstraint('requirement_id')
    )
    op.create_table('supplier_response_rollups',
    sa.Column('rollup_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('main_supplier_actor_id', sa.String(length=36), nullable=False),
    sa.Column('can_accept_order', sa.Boolean(), nullable=True),
    sa.Column('main_capacity_summary', sa.String(length=2048), nullable=True),
    sa.Column('approved_upstream_options_json', sa.JSON(), nullable=False),
    sa.Column('material_basis_json', sa.JSON(), nullable=False),
    sa.Column('trim_basis_json', sa.JSON(), nullable=False),
    sa.Column('subcontract_basis_json', sa.JSON(), nullable=False),
    sa.Column('qc_basis_json', sa.JSON(), nullable=False),
    sa.Column('packaging_basis_json', sa.JSON(), nullable=False),
    sa.Column('logistics_basis_json', sa.JSON(), nullable=False),
    sa.Column('price_basis_json', sa.JSON(), nullable=False),
    sa.Column('lead_time_basis_json', sa.JSON(), nullable=False),
    sa.Column('unresolved_dependencies_json', sa.JSON(), nullable=False),
    sa.Column('risk_flags_json', sa.JSON(), nullable=False),
    sa.Column('completeness_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('recommended_response_to_buyer_en', sa.String(length=4096), nullable=True),
    sa.Column('recommended_response_to_buyer_zh', sa.String(length=4096), nullable=True),
    sa.Column('cad_requirement_packet_id', sa.String(length=36), nullable=True),
    sa.Column('cad_cnc_match_id', sa.String(length=36), nullable=True),
    sa.Column('capability_fit_report_id', sa.String(length=36), nullable=True),
    sa.Column('cnc_parameter_match_summary_json', sa.JSON(), nullable=False),
    sa.Column('can_make_in_house', sa.Boolean(), nullable=True),
    sa.Column('recommended_machine_ids_json', sa.JSON(), nullable=False),
    sa.Column('capability_gaps_json', sa.JSON(), nullable=False),
    sa.Column('upstream_dependency_basis_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['main_supplier_actor_id'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('rollup_id')
    )
    op.create_index('ix_supplier_response_rollups_project_id', 'supplier_response_rollups', ['project_id'], unique=False)
    op.create_table('supplier_score_snapshots',
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('response_speed_score', sa.Float(), nullable=True),
    sa.Column('acceptance_rate_score', sa.Float(), nullable=True),
    sa.Column('on_time_delivery_score', sa.Float(), nullable=True),
    sa.Column('media_cooperation_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('lead_time_accuracy_score', sa.Float(), nullable=True),
    sa.Column('quote_completeness_score', sa.Float(), nullable=True),
    sa.Column('capability_confidence_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('computed_from_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('snapshot_id')
    )
    op.create_table('approval_requests',
    sa.Column('approval_request_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('dependency_id', sa.String(length=36), nullable=True),
    sa.Column('requested_by_actor_id', sa.String(length=36), nullable=False),
    sa.Column('approval_mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=False),
    sa.Column('approved_option_id', sa.String(length=36), nullable=True),
    sa.Column('approved_by_actor_id', sa.String(length=36), nullable=True),
    sa.Column('approved_by_mode', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['dependency_id'], ['dependency_needs.dependency_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['requested_by_actor_id'], ['actors.actor_id'], ),
    sa.PrimaryKeyConstraint('approval_request_id')
    )
    op.create_table('cad_cnc_match_results',
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('cad_requirement_packet_id', sa.String(length=36), nullable=False),
    sa.Column('shop_capability_profile_id', sa.String(length=36), nullable=False),
    sa.Column('can_make_in_house', sa.Boolean(), nullable=False),
    sa.Column('recommended_machine_ids_json', sa.JSON(), nullable=False),
    sa.Column('machine_fit_score', sa.Float(), nullable=False),
    sa.Column('work_envelope_fit', sa.String(length=32), nullable=False),
    sa.Column('material_fit', sa.String(length=32), nullable=False),
    sa.Column('tolerance_fit', sa.String(length=32), nullable=False),
    sa.Column('surface_finish_fit', sa.String(length=32), nullable=False),
    sa.Column('tooling_fit', sa.String(length=32), nullable=False),
    sa.Column('qc_fit', sa.String(length=32), nullable=False),
    sa.Column('schedule_fit', sa.String(length=32), nullable=False),
    sa.Column('required_upstream_dependencies_json', sa.JSON(), nullable=False),
    sa.Column('required_subcontract_dependencies_json', sa.JSON(), nullable=False),
    sa.Column('risk_flags_json', sa.JSON(), nullable=False),
    sa.Column('missing_information_json', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.String(length=4096), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['cad_requirement_packet_id'], ['cad_requirement_packets.packet_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['shop_capability_profile_id'], ['shop_capability_profiles.profile_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index('ix_cad_cnc_match_results_project_id', 'cad_cnc_match_results', ['project_id'], unique=False)
    op.create_table('channel_sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('edge_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('counterparty_actor_id', sa.String(length=36), nullable=True),
    sa.Column('channel_type', sa.String(length=32), nullable=False),
    sa.Column('channel_user_id', sa.String(length=256), nullable=True),
    sa.Column('state_json', sa.JSON(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['counterparty_actor_id'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['edge_id'], ['procurement_edges.edge_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('manufacturing_feature_sets',
    sa.Column('feature_set_id', sa.String(length=36), nullable=False),
    sa.Column('packet_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('required_processes_json', sa.JSON(), nullable=False),
    sa.Column('required_machine_types_json', sa.JSON(), nullable=False),
    sa.Column('min_axis_requirement', sa.Integer(), nullable=True),
    sa.Column('work_envelope_required_json', sa.JSON(), nullable=False),
    sa.Column('material_required', sa.String(length=256), nullable=True),
    sa.Column('tolerance_class', sa.String(length=64), nullable=True),
    sa.Column('surface_finish_class', sa.String(length=64), nullable=True),
    sa.Column('thread_or_hole_features_json', sa.JSON(), nullable=False),
    sa.Column('heat_treatment_required', sa.Boolean(), nullable=False),
    sa.Column('external_process_likely_required', sa.Boolean(), nullable=False),
    sa.Column('qc_required_json', sa.JSON(), nullable=False),
    sa.Column('risk_flags_json', sa.JSON(), nullable=False),
    sa.Column('missing_information_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['cad_requirement_packets.packet_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('feature_set_id')
    )
    op.create_table('role_contexts',
    sa.Column('role_context_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('edge_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('counterparty_actor_id', sa.String(length=36), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('role_reason', sa.String(length=512), nullable=False),
    sa.Column('permissions_json', sa.JSON(), nullable=False),
    sa.Column('can_create_upstream_inquiry', sa.Boolean(), nullable=False),
    sa.Column('can_approve_upstream_option', sa.Boolean(), nullable=False),
    sa.Column('can_submit_response_to_buyer', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['counterparty_actor_id'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['edge_id'], ['procurement_edges.edge_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('role_context_id')
    )
    op.create_index('ix_role_contexts_actor_id', 'role_contexts', ['actor_id'], unique=False)
    op.create_index('ix_role_contexts_project_id', 'role_contexts', ['project_id'], unique=False)
    op.create_table('supplier_inquiries',
    sa.Column('inquiry_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('edge_id', sa.String(length=36), nullable=False),
    sa.Column('from_actor_id', sa.String(length=36), nullable=False),
    sa.Column('to_actor_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=True),
    sa.Column('message_text_en', sa.String(length=4096), nullable=True),
    sa.Column('message_text_zh', sa.String(length=4096), nullable=True),
    sa.Column('message_text_local', sa.String(length=4096), nullable=True),
    sa.Column('requested_fields_json', sa.JSON(), nullable=False),
    sa.Column('required_reply_schema_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['edge_id'], ['procurement_edges.edge_id'], ),
    sa.ForeignKeyConstraint(['from_actor_id'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['requirement_id'], ['structured_requirements.requirement_id'], ),
    sa.ForeignKeyConstraint(['to_actor_id'], ['actors.actor_id'], ),
    sa.PrimaryKeyConstraint('inquiry_id')
    )
    op.create_table('upstream_inquiries',
    sa.Column('upstream_inquiry_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('edge_id', sa.String(length=36), nullable=False),
    sa.Column('dependency_id', sa.String(length=36), nullable=False),
    sa.Column('parent_main_supplier_actor_id', sa.String(length=36), nullable=False),
    sa.Column('upstream_actor_id', sa.String(length=36), nullable=False),
    sa.Column('message_text_en', sa.String(length=4096), nullable=True),
    sa.Column('message_text_zh', sa.String(length=4096), nullable=True),
    sa.Column('requested_fields_json', sa.JSON(), nullable=False),
    sa.Column('required_reply_schema_json', sa.JSON(), nullable=False),
    sa.Column('due_time', sa.String(length=64), nullable=True),
    sa.Column('dispatch_channel', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dependency_id'], ['dependency_needs.dependency_id'], ),
    sa.ForeignKeyConstraint(['edge_id'], ['procurement_edges.edge_id'], ),
    sa.ForeignKeyConstraint(['parent_main_supplier_actor_id'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['upstream_actor_id'], ['actors.actor_id'], ),
    sa.PrimaryKeyConstraint('upstream_inquiry_id')
    )
    op.create_table('upstream_options',
    sa.Column('option_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('dependency_id', sa.String(length=36), nullable=False),
    sa.Column('upstream_actor_id', sa.String(length=36), nullable=False),
    sa.Column('option_label', sa.String(length=32), nullable=False),
    sa.Column('price_summary', sa.String(length=256), nullable=True),
    sa.Column('lead_time_summary', sa.String(length=256), nullable=True),
    sa.Column('risk_summary', sa.String(length=512), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=1024), nullable=True),
    sa.Column('response_ids_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dependency_id'], ['dependency_needs.dependency_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['upstream_actor_id'], ['actors.actor_id'], ),
    sa.PrimaryKeyConstraint('option_id')
    )
    op.create_table('capability_fit_reports',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('cad_cnc_match_id', sa.String(length=36), nullable=False),
    sa.Column('buyer_facing_summary_en', sa.String(length=4096), nullable=True),
    sa.Column('buyer_facing_summary_zh', sa.String(length=4096), nullable=True),
    sa.Column('internal_summary', sa.String(length=4096), nullable=True),
    sa.Column('can_quote_now', sa.Boolean(), nullable=False),
    sa.Column('can_make_in_house', sa.Boolean(), nullable=False),
    sa.Column('recommended_next_actions_json', sa.JSON(), nullable=False),
    sa.Column('required_upstream_inquiries_json', sa.JSON(), nullable=False),
    sa.Column('required_subcontractor_inquiries_json', sa.JSON(), nullable=False),
    sa.Column('risk_flags_json', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['cad_cnc_match_id'], ['cad_cnc_match_results.match_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('execution_events',
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('edge_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('role_context_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('source_channel', sa.String(length=32), nullable=True),
    sa.Column('source_message_id', sa.String(length=36), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['edge_id'], ['procurement_edges.edge_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['role_context_id'], ['role_contexts.role_context_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_execution_events_created_at', 'execution_events', ['created_at'], unique=False)
    op.create_index('ix_execution_events_event_type', 'execution_events', ['event_type'], unique=False)
    op.create_index('ix_execution_events_project_id', 'execution_events', ['project_id'], unique=False)
    op.create_table('messages',
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('edge_id', sa.String(length=36), nullable=True),
    sa.Column('role_context_id', sa.String(length=36), nullable=True),
    sa.Column('sender_actor_id', sa.String(length=36), nullable=True),
    sa.Column('receiver_actor_id', sa.String(length=36), nullable=True),
    sa.Column('channel_type', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('raw_text', sa.String(length=8192), nullable=True),
    sa.Column('normalized_text', sa.String(length=8192), nullable=True),
    sa.Column('attachments_json', sa.JSON(), nullable=False),
    sa.Column('parsed_intent', sa.String(length=128), nullable=True),
    sa.Column('parsed_entities_json', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['edge_id'], ['procurement_edges.edge_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['receiver_actor_id'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['role_context_id'], ['role_contexts.role_context_id'], ),
    sa.ForeignKeyConstraint(['sender_actor_id'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['channel_sessions.session_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index('ix_messages_project_id', 'messages', ['project_id'], unique=False)
    op.create_index('ix_messages_session_id', 'messages', ['session_id'], unique=False)
    op.create_table('supplier_responses',
    sa.Column('response_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('edge_id', sa.String(length=36), nullable=False),
    sa.Column('inquiry_id', sa.String(length=36), nullable=True),
    sa.Column('from_actor_id', sa.String(length=36), nullable=False),
    sa.Column('to_actor_id', sa.String(length=36), nullable=False),
    sa.Column('can_supply', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('moq', sa.Float(), nullable=True),
    sa.Column('available_quantity', sa.Float(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('earliest_dispatch_date', sa.String(length=32), nullable=True),
    sa.Column('capacity_basis_json', sa.JSON(), nullable=False),
    sa.Column('material_basis_json', sa.JSON(), nullable=False),
    sa.Column('subcontract_basis_json', sa.JSON(), nullable=False),
    sa.Column('qc_basis_json', sa.JSON(), nullable=False),
    sa.Column('logistics_basis_json', sa.JSON(), nullable=False),
    sa.Column('risk_flags_json', sa.JSON(), nullable=False),
    sa.Column('raw_message', sa.String(length=8192), nullable=True),
    sa.Column('parsed_json', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('completeness_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['edge_id'], ['procurement_edges.edge_id'], ),
    sa.ForeignKeyConstraint(['from_actor_id'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['inquiry_id'], ['supplier_inquiries.inquiry_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['to_actor_id'], ['actors.actor_id'], ),
    sa.PrimaryKeyConstraint('response_id')
    )
    op.create_table('upstream_responses',
    sa.Column('upstream_response_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('edge_id', sa.String(length=36), nullable=False),
    sa.Column('upstream_inquiry_id', sa.String(length=36), nullable=False),
    sa.Column('dependency_id', sa.String(length=36), nullable=False),
    sa.Column('from_actor_id', sa.String(length=36), nullable=False),
    sa.Column('can_supply', sa.Boolean(), nullable=False),
    sa.Column('matched_specs_json', sa.JSON(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('moq', sa.Float(), nullable=True),
    sa.Column('available_quantity', sa.Float(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('earliest_dispatch_date', sa.String(length=32), nullable=True),
    sa.Column('quality_notes', sa.String(length=1024), nullable=True),
    sa.Column('substitute_options_json', sa.JSON(), nullable=False),
    sa.Column('risk_flags_json', sa.JSON(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('completeness_score', sa.Float(), nullable=False),
    sa.Column('raw_message', sa.String(length=8192), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dependency_id'], ['dependency_needs.dependency_id'], ),
    sa.ForeignKeyConstraint(['edge_id'], ['procurement_edges.edge_id'], ),
    sa.ForeignKeyConstraint(['from_actor_id'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['upstream_inquiry_id'], ['upstream_inquiries.upstream_inquiry_id'], ),
    sa.PrimaryKeyConstraint('upstream_response_id')
    )
    op.create_table('entity_dynamic_values',
    sa.Column('value_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('field_id', sa.String(length=36), nullable=False),
    sa.Column('field_value', sa.String(length=1024), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=True),
    sa.Column('source_message_id', sa.String(length=36), nullable=True),
    sa.Column('source_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['field_definitions.field_id'], ),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['artifacts.artifact_id'], ),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.message_id'], ),
    sa.PrimaryKeyConstraint('value_id')
    )
    op.create_index('ix_entity_dynamic_values_entity_type_id', 'entity_dynamic_values', ['entity_type', 'entity_id'], unique=False)
    op.create_table('observed_fields',
    sa.Column('observed_field_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('source_message_id', sa.String(length=36), nullable=True),
    sa.Column('source_artifact_id', sa.String(length=36), nullable=True),
    sa.Column('candidate_field_name', sa.String(length=128), nullable=False),
    sa.Column('normalized_field_name', sa.String(length=128), nullable=True),
    sa.Column('candidate_value', sa.String(length=512), nullable=True),
    sa.Column('candidate_unit', sa.String(length=32), nullable=True),
    sa.Column('normalized_value', sa.String(length=512), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('evidence_text', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['artifacts.artifact_id'], ),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.message_id'], ),
    sa.PrimaryKeyConstraint('observed_field_id')
    )
    op.create_index('ix_observed_fields_normalized_field_name', 'observed_fields', ['normalized_field_name'], unique=False)
    op.create_table('supplier_profile_updates',
    sa.Column('update_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('update_type', sa.String(length=64), nullable=False),
    sa.Column('previous_value_json', sa.JSON(), nullable=False),
    sa.Column('new_value_json', sa.JSON(), nullable=False),
    sa.Column('evidence_event_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actors.actor_id'], ),
    sa.ForeignKeyConstraint(['evidence_event_id'], ['execution_events.event_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('update_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('supplier_profile_updates')
    op.drop_index('ix_observed_fields_normalized_field_name', table_name='observed_fields')
    op.drop_table('observed_fields')
    op.drop_index('ix_entity_dynamic_values_entity_type_id', table_name='entity_dynamic_values')
    op.drop_table('entity_dynamic_values')
    op.drop_table('upstream_responses')
    op.drop_table('supplier_responses')
    op.drop_index('ix_messages_session_id', table_name='messages')
    op.drop_index('ix_messages_project_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_execution_events_project_id', table_name='execution_events')
    op.drop_index('ix_execution_events_event_type', table_name='execution_events')
    op.drop_index('ix_execution_events_created_at', table_name='execution_events')
    op.drop_table('execution_events')
    op.drop_table('capability_fit_reports')
    op.drop_table('upstream_options')
    op.drop_table('upstream_inquiries')
    op.drop_table('supplier_inquiries')
    op.drop_index('ix_role_contexts_project_id', table_name='role_contexts')
    op.drop_index('ix_role_contexts_actor_id', table_name='role_contexts')
    op.drop_table('role_contexts')
    op.drop_table('manufacturing_feature_sets')
    op.drop_table('channel_sessions')
    op.drop_index('ix_cad_cnc_match_results_project_id', table_name='cad_cnc_match_results')
    op.drop_table('cad_cnc_match_results')
    op.drop_table('approval_requests')
    op.drop_table('supplier_score_snapshots')
    op.drop_index('ix_supplier_response_rollups_project_id', table_name='supplier_response_rollups')
    op.drop_table('supplier_response_rollups')
    op.drop_table('structured_requirements')
    op.drop_index('ix_procurement_edges_to_actor_id', table_name='procurement_edges')
    op.drop_index('ix_procurement_edges_status', table_name='procurement_edges')
    op.drop_index('ix_procurement_edges_project_id', table_name='procurement_edges')
    op.drop_index('ix_procurement_edges_parent_edge_id', table_name='procurement_edges')
    op.drop_index('ix_procurement_edges_from_actor_id', table_name='procurement_edges')
    op.drop_index('ix_procurement_edges_edge_type', table_name='procurement_edges')
    op.drop_table('procurement_edges')
    op.drop_table('field_promotion_decisions')
    op.drop_table('field_aliases')
    op.drop_table('dependency_needs')
    op.drop_table('cad_requirement_packets')
    op.drop_table('artifacts')
    op.drop_table('shop_capability_profiles')
    op.drop_index('ix_projects_status', table_name='projects')
    op.drop_index('ix_projects_original_buyer_actor_id', table_name='projects')
    op.drop_index('ix_projects_main_supplier_actor_id', table_name='projects')
    op.drop_index('ix_projects_created_at', table_name='projects')
    op.drop_index('ix_projects_category', table_name='projects')
    op.drop_table('projects')
    op.drop_table('field_proposals')
    op.drop_index('ix_field_definitions_normalized_field_name', table_name='field_definitions')
    op.drop_table('field_definitions')
    op.drop_table('unit_dictionary')
    op.drop_table('schema_registry')
    op.drop_table('legal_notices')
    op.drop_index('ix_actors_actor_type', table_name='actors')
    op.drop_table('actors')
    # ### end Alembic commands ###
