from enum import Enum


class ActorType(str, Enum):
    buyer = "buyer"
    manufacturer = "manufacturer"
    trading_company = "trading_company"
    material_supplier = "material_supplier"
    fabric_supplier = "fabric_supplier"
    trim_supplier = "trim_supplier"
    component_supplier = "component_supplier"
    subcontractor = "subcontractor"
    qc_provider = "qc_provider"
    packaging_supplier = "packaging_supplier"
    logistics_provider = "logistics_provider"
    education_research = "education_research"
    unknown = "unknown"


class RoleType(str, Enum):
    ORIGINAL_BUYER = "ORIGINAL_BUYER"
    MAIN_M_SIDE = "MAIN_M_SIDE"
    UPSTREAM_B_SIDE = "UPSTREAM_B_SIDE"
    UPSTREAM_M_SIDE = "UPSTREAM_M_SIDE"
    QC_SIDE = "QC_SIDE"
    LOGISTICS_SIDE = "LOGISTICS_SIDE"
    SYSTEM = "SYSTEM"
    UNKNOWN = "UNKNOWN"
    # Trading company / salesperson variable-M roles (Neutral Actor Model)
    CUSTOMER_FACING_M_SIDE = "CUSTOMER_FACING_M_SIDE"
    TRADE_MERCHANDISER = "TRADE_MERCHANDISER"


class ProjectStatus(str, Enum):
    CREATED = "CREATED"
    B_INQUIRY_STRUCTURED = "B_INQUIRY_STRUCTURED"
    MAIN_SUPPLIER_RECEIVED = "MAIN_SUPPLIER_RECEIVED"
    UPSTREAM_DEPENDENCY_PLANNED = "UPSTREAM_DEPENDENCY_PLANNED"
    UPSTREAM_INQUIRIES_SENT = "UPSTREAM_INQUIRIES_SENT"
    UPSTREAM_RESPONSES_RECEIVED = "UPSTREAM_RESPONSES_RECEIVED"
    UPSTREAM_OPTIONS_READY = "UPSTREAM_OPTIONS_READY"
    UPSTREAM_OPTION_APPROVED = "UPSTREAM_OPTION_APPROVED"
    SUPPLIER_RESPONSE_ROLLED_UP = "SUPPLIER_RESPONSE_ROLLED_UP"
    SUPPLIER_RESPONSE_SUBMITTED_TO_BUYER = "SUPPLIER_RESPONSE_SUBMITTED_TO_BUYER"
    ORDER_CONFIRMED = "ORDER_CONFIRMED"
    IN_EXECUTION = "IN_EXECUTION"
    CLOSED = "CLOSED"
    CANCELLED = "CANCELLED"


class EdgeType(str, Enum):
    BUYER_TO_MAIN_SUPPLIER = "BUYER_TO_MAIN_SUPPLIER"
    MAIN_SUPPLIER_TO_MATERIAL_SUPPLIER = "MAIN_SUPPLIER_TO_MATERIAL_SUPPLIER"
    MAIN_SUPPLIER_TO_FABRIC_SUPPLIER = "MAIN_SUPPLIER_TO_FABRIC_SUPPLIER"
    MAIN_SUPPLIER_TO_TRIM_SUPPLIER = "MAIN_SUPPLIER_TO_TRIM_SUPPLIER"
    MAIN_SUPPLIER_TO_COMPONENT_SUPPLIER = "MAIN_SUPPLIER_TO_COMPONENT_SUPPLIER"
    MAIN_SUPPLIER_TO_SUBCONTRACTOR = "MAIN_SUPPLIER_TO_SUBCONTRACTOR"
    MAIN_SUPPLIER_TO_PACKAGING_SUPPLIER = "MAIN_SUPPLIER_TO_PACKAGING_SUPPLIER"
    MAIN_SUPPLIER_TO_QC_PROVIDER = "MAIN_SUPPLIER_TO_QC_PROVIDER"
    MAIN_SUPPLIER_TO_LOGISTICS_PROVIDER = "MAIN_SUPPLIER_TO_LOGISTICS_PROVIDER"


class EdgeStatus(str, Enum):
    DRAFT = "DRAFT"
    SENT = "SENT"
    RESPONDED = "RESPONDED"
    OPTIONS_READY = "OPTIONS_READY"
    APPROVED = "APPROVED"
    ROLLED_UP = "ROLLED_UP"
    REJECTED = "REJECTED"
    CLOSED = "CLOSED"


class ChannelType(str, Enum):
    openclaw = "openclaw"
    wechat = "wechat"
    whatsapp = "whatsapp"
    line = "line"
    email = "email"
    web_fallback = "web_fallback"
    mock = "mock"


class ArtifactType(str, Enum):
    cad = "cad"
    step = "step"
    pdf = "pdf"
    bom = "bom"
    image = "image"
    video = "video"
    spreadsheet = "spreadsheet"
    manual_text = "manual_text"
    other = "other"


class ProductTier(str, Enum):
    free = "free"
    professional_free = "professional_free"
    plus = "plus"
    pro = "pro"
    enterprise_cap = "enterprise_cap"


class ApprovalMode(str, Enum):
    human = "human"
    authorized_agent = "authorized_agent"
    automatic_low_risk = "automatic_low_risk"


class ApprovalStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class DynamicFieldStatus(str, Enum):
    observed = "observed"
    proposed = "proposed"
    approved = "approved"
    rejected = "rejected"
    deprecated = "deprecated"
    promoted = "promoted"


class ExecutionEventType(str, Enum):
    ROLE_CONTEXT_RESOLVED = "ROLE_CONTEXT_RESOLVED"
    ROLE_SWITCH_OCCURRED = "ROLE_SWITCH_OCCURRED"
    B_INQUIRY_CREATED = "B_INQUIRY_CREATED"
    M_SIDE_RECEIVED_BUYER_INQUIRY = "M_SIDE_RECEIVED_BUYER_INQUIRY"
    UPSTREAM_DEPENDENCY_PLANNED = "UPSTREAM_DEPENDENCY_PLANNED"
    UPSTREAM_INQUIRY_CREATED = "UPSTREAM_INQUIRY_CREATED"
    UPSTREAM_INQUIRY_DISPATCHED = "UPSTREAM_INQUIRY_DISPATCHED"
    UPSTREAM_RESPONSE_RECEIVED = "UPSTREAM_RESPONSE_RECEIVED"
    UPSTREAM_RESPONSE_PARSED = "UPSTREAM_RESPONSE_PARSED"
    UPSTREAM_OPTIONS_GENERATED = "UPSTREAM_OPTIONS_GENERATED"
    UPSTREAM_OPTION_APPROVAL_REQUESTED = "UPSTREAM_OPTION_APPROVAL_REQUESTED"
    UPSTREAM_OPTION_APPROVED = "UPSTREAM_OPTION_APPROVED"
    SUPPLIER_RESPONSE_ROLLUP_GENERATED = "SUPPLIER_RESPONSE_ROLLUP_GENERATED"
    SUPPLIER_RESPONSE_ROLLUP_SUBMITTED_TO_B_SIDE = "SUPPLIER_RESPONSE_ROLLUP_SUBMITTED_TO_B_SIDE"
    CAD_REQUIREMENT_PACKET_CREATED = "CAD_REQUIREMENT_PACKET_CREATED"
    CAD_FEATURES_EXTRACTED = "CAD_FEATURES_EXTRACTED"
    SHOP_CAPABILITY_PROFILE_LOADED = "SHOP_CAPABILITY_PROFILE_LOADED"
    CAD_CNC_MATCH_STARTED = "CAD_CNC_MATCH_STARTED"
    CAD_CNC_MATCH_COMPLETED = "CAD_CNC_MATCH_COMPLETED"
    MACHINE_PARAMETER_MATCHED = "MACHINE_PARAMETER_MATCHED"
    MACHINE_PARAMETER_GAP_FOUND = "MACHINE_PARAMETER_GAP_FOUND"
    CAPABILITY_FIT_REPORT_CREATED = "CAPABILITY_FIT_REPORT_CREATED"
    DEPENDENCY_CREATED_FROM_CAD_CNC_MATCH = "DEPENDENCY_CREATED_FROM_CAD_CNC_MATCH"
    PROFESSIONAL_FREE_FILE_WARNING_SHOWN = "PROFESSIONAL_FREE_FILE_WARNING_SHOWN"
    PROFESSIONAL_FREE_CAP_LIMITATION_ACKNOWLEDGED = "PROFESSIONAL_FREE_CAP_LIMITATION_ACKNOWLEDGED"
    CAPABILITY_CONNECTOR_REGISTERED = "CAPABILITY_CONNECTOR_REGISTERED"
    CAPABILITY_CHECK_REQUESTED = "CAPABILITY_CHECK_REQUESTED"
    MACHINACHECK_LIKE_ASSESSMENT_STARTED = "MACHINACHECK_LIKE_ASSESSMENT_STARTED"
    MACHINACHECK_LIKE_ASSESSMENT_COMPLETED = "MACHINACHECK_LIKE_ASSESSMENT_COMPLETED"
    CAPABILITY_EVIDENCE_ATTACHED = "CAPABILITY_EVIDENCE_ATTACHED"
    CAPABILITY_RISK_FLAGGED = "CAPABILITY_RISK_FLAGGED"
    CAPABILITY_CONFIDENCE_SCORE_UPDATED = "CAPABILITY_CONFIDENCE_SCORE_UPDATED"
    ORDER_CONFIRMED = "ORDER_CONFIRMED"
    PRODUCTION_UPDATE_RECEIVED = "PRODUCTION_UPDATE_RECEIVED"
    QC_UPDATE_RECEIVED = "QC_UPDATE_RECEIVED"
    EXCEPTION_REPORTED = "EXCEPTION_REPORTED"
    LOGISTICS_HANDOVER_RECEIVED = "LOGISTICS_HANDOVER_RECEIVED"
    ORDER_CLOSED = "ORDER_CLOSED"
    # OpenClaw channel event types
    OPENCLAW_EVENT_RECEIVED = "OPENCLAW_EVENT_RECEIVED"
    OPENCLAW_B_SIDE_PROJECT_CREATED = "OPENCLAW_B_SIDE_PROJECT_CREATED"
    OPENCLAW_B_SIDE_PROJECT_UPDATED = "OPENCLAW_B_SIDE_PROJECT_UPDATED"
    OPENCLAW_SUPPLIER_DRAFT_CREATED = "OPENCLAW_SUPPLIER_DRAFT_CREATED"
    OPENCLAW_SUPPLIER_DRAFT_APPROVED = "OPENCLAW_SUPPLIER_DRAFT_APPROVED"
    OPENCLAW_SUPPLIER_DRAFT_REJECTED = "OPENCLAW_SUPPLIER_DRAFT_REJECTED"
    OPENCLAW_M_SIDE_SUPPLIER_REPLY_RECEIVED = "OPENCLAW_M_SIDE_SUPPLIER_REPLY_RECEIVED"
    OPENCLAW_CONVERSATION_BINDING_CREATED = "OPENCLAW_CONVERSATION_BINDING_CREATED"
