"""Enumerations used throughout the GLTG library."""

from enum import Enum


class ApparelNodeType(str, Enum):
    BUYER_REQUIREMENT_CONFIRMATION = "BUYER_REQUIREMENT_CONFIRMATION"
    DESIGN_OR_TECH_PACK_CONFIRMATION = "DESIGN_OR_TECH_PACK_CONFIRMATION"
    FABRIC_SELECTION = "FABRIC_SELECTION"
    FABRIC_AVAILABILITY_CONFIRMATION = "FABRIC_AVAILABILITY_CONFIRMATION"
    FABRIC_ORDERING = "FABRIC_ORDERING"
    FABRIC_DYEING_OR_PRINTING = "FABRIC_DYEING_OR_PRINTING"
    FABRIC_FINISHING = "FABRIC_FINISHING"
    FABRIC_TESTING = "FABRIC_TESTING"
    TRIM_SELECTION = "TRIM_SELECTION"
    TRIM_AVAILABILITY_CONFIRMATION = "TRIM_AVAILABILITY_CONFIRMATION"
    TRIM_ORDERING = "TRIM_ORDERING"
    PACKAGING_MATERIAL_CONFIRMATION = "PACKAGING_MATERIAL_CONFIRMATION"
    SAMPLE_MAKING = "SAMPLE_MAKING"
    SAMPLE_APPROVAL = "SAMPLE_APPROVAL"
    PP_SAMPLE_APPROVAL = "PP_SAMPLE_APPROVAL"
    PRODUCTION_SLOT_BOOKING = "PRODUCTION_SLOT_BOOKING"
    CUTTING = "CUTTING"
    SEWING = "SEWING"
    WASHING_OR_FINISHING = "WASHING_OR_FINISHING"
    INLINE_QC = "INLINE_QC"
    FINAL_QC = "FINAL_QC"
    REWORK_IF_NEEDED = "REWORK_IF_NEEDED"
    PACKING = "PACKING"
    LOGISTICS_BOOKING = "LOGISTICS_BOOKING"
    CUSTOMS_OR_EXPORT_DOCS = "CUSTOMS_OR_EXPORT_DOCS"
    SHIPMENT = "SHIPMENT"
    BUYER_RECEIPT = "BUYER_RECEIPT"
    BUYER_SIGN_OFF = "BUYER_SIGN_OFF"


class DependencyType(str, Enum):
    FINISH_TO_START = "FINISH_TO_START"
    START_TO_START = "START_TO_START"
    FINISH_TO_FINISH = "FINISH_TO_FINISH"
    MATERIAL_READY_BEFORE_START = "MATERIAL_READY_BEFORE_START"
    APPROVAL_READY_BEFORE_START = "APPROVAL_READY_BEFORE_START"
    CAPACITY_SLOT_REQUIRED = "CAPACITY_SLOT_REQUIRED"
    OPTIONAL = "OPTIONAL"
    CONDITIONAL = "CONDITIONAL"


class NodeStatus(str, Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    BLOCKED = "BLOCKED"
    SKIPPED = "SKIPPED"


class ConfidenceLevel(str, Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    VERY_LOW = "VERY_LOW"


class EvidenceSourceType(str, Enum):
    ACTUAL_PROGRESS = "ACTUAL_PROGRESS"
    SUPPLIER_CONFIRMATION = "SUPPLIER_CONFIRMATION"
    HISTORICAL_MEMORY = "HISTORICAL_MEMORY"
    SUPPLIER_QUOTE = "SUPPLIER_QUOTE"
    CATEGORY_BASELINE = "CATEGORY_BASELINE"
    AI_ESTIMATE = "AI_ESTIMATE"


class RiskFlagCode(str, Enum):
    LIMITED_COMPETITION = "LIMITED_COMPETITION"
    LIMITED_COMPARISON = "LIMITED_COMPARISON"
    NO_FEASIBLE_OPTION = "NO_FEASIBLE_OPTION"
    MISSING_FABRIC_SUPPLIER = "MISSING_FABRIC_SUPPLIER"
    MISSING_PRODUCTION_CAPACITY = "MISSING_PRODUCTION_CAPACITY"
    LOW_SUPPLIER_RELIABILITY = "LOW_SUPPLIER_RELIABILITY"
    TIGHT_DEADLINE = "TIGHT_DEADLINE"
    MISSING_SAMPLE_APPROVAL = "MISSING_SAMPLE_APPROVAL"
    HIGH_REWORK_RISK = "HIGH_REWORK_RISK"
    LOGISTICS_RISK = "LOGISTICS_RISK"
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"
    CAPACITY_CONSTRAINT = "CAPACITY_CONSTRAINT"
    SINGLE_SOURCE_RISK = "SINGLE_SOURCE_RISK"
    QC_RISK = "QC_RISK"
    CUSTOMS_RISK = "CUSTOMS_RISK"


class FeasibilityStatus(str, Enum):
    FEASIBLE = "FEASIBLE"
    LIMITED_OPTIONS = "LIMITED_OPTIONS"
    NO_FEASIBLE_OPTION = "NO_FEASIBLE_OPTION"
    REQUIRES_EXPEDITE = "REQUIRES_EXPEDITE"
    HUMAN_REVIEW_REQUIRED = "HUMAN_REVIEW_REQUIRED"


class OptionStatus(str, Enum):
    FEASIBLE = "FEASIBLE"
    TIGHT = "TIGHT"
    REQUIRES_EXPEDITE = "REQUIRES_EXPEDITE"
    INFEASIBLE = "INFEASIBLE"


class DeliveryMode(str, Enum):
    FULL_DELIVERY = "FULL_DELIVERY"
    PARTIAL_DELIVERY = "PARTIAL_DELIVERY"
    SPLIT_SHIPMENT = "SPLIT_SHIPMENT"
    PARALLEL_FACTORY_PRODUCTION = "PARALLEL_FACTORY_PRODUCTION"
    SEQUENTIAL_FACTORY_PRODUCTION = "SEQUENTIAL_FACTORY_PRODUCTION"


class ProgressEventType(str, Enum):
    SUPPLIER_CONFIRMED = "SUPPLIER_CONFIRMED"
    MATERIAL_DELAYED = "MATERIAL_DELAYED"
    TRIM_DELAYED = "TRIM_DELAYED"
    SAMPLE_APPROVAL_DELAYED = "SAMPLE_APPROVAL_DELAYED"
    PRODUCTION_PROGRESS_UPDATE = "PRODUCTION_PROGRESS_UPDATE"
    QC_FAILED = "QC_FAILED"
    REWORK_STARTED = "REWORK_STARTED"
    REWORK_COMPLETED = "REWORK_COMPLETED"
    LOGISTICS_DELAYED = "LOGISTICS_DELAYED"
    BUYER_APPROVAL_DELAYED = "BUYER_APPROVAL_DELAYED"
    NODE_COMPLETED = "NODE_COMPLETED"
    NODE_STARTED = "NODE_STARTED"


class ParticipantType(str, Enum):
    FABRIC_SUPPLIER = "FABRIC_SUPPLIER"
    TRIM_SUPPLIER = "TRIM_SUPPLIER"
    GARMENT_FACTORY = "GARMENT_FACTORY"
    QC_INSPECTOR = "QC_INSPECTOR"
    LOGISTICS_PROVIDER = "LOGISTICS_PROVIDER"
    PACKAGING_SUPPLIER = "PACKAGING_SUPPLIER"
    BUYING_HOUSE = "BUYING_HOUSE"
    BUYER = "BUYER"


class OptionLabel(str, Enum):
    FASTEST = "FASTEST"
    MOST_RELIABLE = "MOST_RELIABLE"
    BEST_COMMERCIAL_BALANCE = "BEST_COMMERCIAL_BALANCE"


class CostImpactLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    VERY_HIGH = "VERY_HIGH"


class RiskImpactLevel(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    VERY_HIGH = "VERY_HIGH"
